#ifndef D_NUCLEOL053R8T6
#define D_NUCLEOL053R8T6
/*
 * Buttons and LEDs on NUCLEO Board.
 */
#define NUCLEO_BUTTON_IOPENER_BIT RCC_IOPENR_GPIOCEN // Bit for clk for GPIOC enabling.
#define NUCLEO_BUTTON_PORT GPIOC
#define NUCLEO_BUTTON_PIN 0x0D
#define NUCLEO_BUTTON_PIN_MASK 1 << NUCLEO_BUTTON_PIN

#define NUCLEO_LED_GREEN_IOPENER_BIT RCC_IOPENR_GPIOAEN // Bit for clk for GPIOA enabling.
#define NUCLEO_LED_GREEN_PORT GPIOA
#define NUCLEO_LED_GREEN_PIN 0x05
#define NUCLEO_LED_GREEN_PIN_MASK 1 << NUCLEO_LED_GREEN_PIN



#define NUCLEO_USART1_PORT GPIOA
#define NUCLEO_USART1_PIN_TX 9ul
#define NUCLEO_USART1_PIN_RX 10ul
#define NUCLEO_USART1_PIN_TX_MASK 1 << NUCLEO_USART1_PIN_TX
#define NUCLEO_USART1_PIN_RX_MASK 1 << NUCLEO_USART1_PIN_RX
#define NUCLEO_USART1_ALT_FUNC	4ul


#define NUCLEO_USART2_PORT GPIOA
#define NUCLEO_USART2_PIN_TX 0x02
#define NUCLEO_USART2_PIN_RX 0x03
#define NUCLEO_USART2_PIN_TX_MASK 1 << NUCLEO_USART2_PIN_TX
#define NUCLEO_USART2_PIN_RX_MASK 1 << NUCLEO_USART2_PIN_RX
#define NUCLEO_USART2_ALT_FUNC	4ul
#define NUCLEO_USART2_IOPENER_BIT RCC_IOPENR_GPIOAEN // Bit for clk for GPIOA enabling.

#define NUCLEO_SPI1_PORT GPIOA
#define NUCLEO_SPI1_PIN_NSS		15ul //4ul //two pins available
#define NUCLEO_SPI1_PIN_SCK		5ul
#define NUCLEO_SPI1_PIN_MISO	11ul //11 //two pins available
#define NUCLEO_SPI1_PIN_MOSI	12ul //7ul //two pins available
#define NUCLEO_SPI1_PIN_NSS_MASK 	1 << NUCLEO_SPI1_PIN_NSS
#define NUCLEO_SPI1_PIN_SCK_MASK    1 << NUCLEO_SPI1_PIN_SCK
#define NUCLEO_SPI1_PIN_MISO_MASK   1 << NUCLEO_SPI1_PIN_MISO
#define NUCLEO_SPI1_PIN_MOSI_MASK   1 << NUCLEO_SPI1_PIN_MOSI
#define NUCLEO_SPI1_ALT_FUNC	0ul

#endif //D_NUCLEOL053R8T6
